#!/bin/bash

file=quicksum.txt
rm $file
for i in $*
do
    echo "$i Module Summary" >> $file
    echo "" >> $file
    echo "$i Options" >> $file
    grep "public variable" $i >> $file
    echo "" >> $file
    echo "$i Commands and States" >> $file
    egrep "public method|state|method constructor" $i | grep -v "state ns" >> $file
    echo "" >> $file
    echo "" >> $file
done

