#
#
#
include ../Makefile.defs

LIBNAME=zlib
SRCS=ZException.cpp adsRTreeCore.cpp

##############################################
# Add custom targets below the following line.
include ../Makefile.rules
