#
#
#
include ../Makefile.defs

LIBNAME=tm
TCLIF=ZSession.ti
SRCS=tm.cpp ZObject.cpp ZSession.cpp ZSession_Tcl.cpp ZFactory.cpp ZNamespace.cpp ZTechModuleMgr.cpp

##############################################
# Add custom targets below the following line.
include ../Makefile.rules
