#
#
#
include ../../Makefile.defs

LIBNAME=db_conn
SRCS= tmg_conn.cpp wOrder.cpp tmg_conn_g.cpp tmg_conn_s.cpp tmg_conn_w.cpp

##############################################
# Add custom targets below the following line.
include ../../Makefile.rules
