DIFFLOGS=test.diff \
	test.tempdiff \

LOGS=test.log \
	test.templog \

%.diff: %.log
	diff -b -B $< $<.GOLD > $*.tempdiff
	mv $*.tempdiff $*.diff

%.log: %.exe
	./$< > $*.templog
	mv $*.templog $*.log

.PRECIOUS: %.log

.PHONY: cvsup goldup

test.diff:

test: test.diff

upcvs:
	cvs update

upgold:
	cp test.log test.log.GOLD
	cvs commit test.log.GOLD

.PHONY: cleanlog cleandiff clean

cleanlog:
	-rm -f test.log test.tmplog

cleandiff:
	-rm -f $(DIFFLOGS)


cleantest: cleanlog cleandiff
