#!/usr/bin/env tclsh
##
## Testing Tool - tt.tcl
## Author: Mattias Hembruch

package require Itcl

source globals.tcl
source util.tcl
source timer.tcl
source group.tcl
source create.tcl
source parse.tcl
source test.tcl
source config.tcl

Config cfg

cfg find_zr

parse_env

set rcline ""
if { [file exists $rcglobal] } { append rcline [readfile $rcglobal] }
#if { [file exists $rclocal] } { append rcline [readfile $rclocal] }

set testlist [eval parse $rcline $argv]


if { [llength $testlist] != 0 } {
    if { $ctype != "show" } {
        cfg set_tests $testlist
        cfg execute_tests
        cfg show_results
    }
}

closelog
