#
#
#
include ../../Makefile.defs

TCLIF=TMP.ti

LIBNAME=TMP_tcl

SRCS= TMP.cpp TMP_Tcl.cpp 

##############################################
# Add custom targets below the following line.
include ../../Makefile.rules
