#
#
#
include ../../Makefile.defs

TCLIF=PDN.ti

LIBNAME=PDN_tcl

SRCS= PDN.cpp PDN_Tcl.cpp 

##############################################
# Add custom targets below the following line.
include ../../Makefile.rules
