#include <errno.h>
#include "PDN.h"    // Class defintions of Interface
#include "../SHAPES.h"

#include "PDN_Tcl.h" // Generated by the ti utility program
#include <logger.h>

#define TCL_IN_ARGS(name) name * in_args = (name *) in
#define TCL_OUT_ARGS(name) name * out_args = (name *) out

BEGIN_NAMESPACE_ADS

PDN::PDN(ZArgs * in, ZArgs * out) : ZTechModule<PDN>(in, out)
{
	notice(0, "Created an instance of PDN\n");
	_main = new SHAPES(_db);
}
PDN::~PDN()
{
	// delete _main;
}
/*************************************** module functions *****************/
TCL_METHOD(PDN::print_macros)
{
	notice(0, "PDN::print_macros\n");
	TCL_IN_ARGS(ZIn_PDN_print_macros);
	_main->printMacros(in_args->file());
	return TCL_OK;
}
END_NAMESPACE_ADS
