#
#
#
include ../Makefile.defs

LIBNAME=zutil
SRCS= misc_functions.cpp atypes.cpp files.cpp name.cpp mem.cpp parse.cpp graph.cpp kdtree.cpp gz.cpp debug_filter.cpp poly_decomp.cpp b100.cpp xf.cpp dgraph.cpp charBuffer.cpp

##############################################
# Add custom targets below the following line.
include ../Makefile.rules
