#
#
#
include ../../Makefile.defs

TCLIF=ZDB.ti
LIBNAME=db_tcl
SRCS= ZDB.cpp ZDB_Tcl.cpp test_eco.cpp rpt_region.cpp sdc_db.cpp

##############################################
# Add custom targets below the following line.
include ../../Makefile.rules
