#
#
#
include ../Makefile.defs

CXXFLAGS+=-I../tmg $(STAINC)

LIBNAME= replace

TCLIF=rpl.ti

SRCS=  \
	replaceMain.cpp \
        rpl.cpp \
	rpl_Tcl.cpp

CMAKE_INCLUDES=
		

                

##############################################
# Add custom targets below the following line.
include ../Makefile.rules

