#
#
#
include ../Makefile.defs

LIBNAME=sver
SRCS=   sver.cpp sver_token.cpp sver_parser.cpp sver_names.cpp

YACC_SRC=sver_parser.y
YACC_PREFIX=sver_parser_
LEX_SRC=sver_token.l
LEX_PREFIX=sver_parser_

##############################################
# Add custom targets below the following line.
include ../Makefile.rules

