#
# This is a example makefile for creating a new library
#

##################################
# Define variables below this line
include ../makefile.defs

#
# You need to define the following variables.
#     SRCS=foo.cpp ...
#
# DEFINES= <Addtional #define defintions>
# LIBNAME= <Name of library>
# TCLIF= <Name of tcl interface file>
# SRCS= <List of source file .cpp or .c>
# YACC_SRC= <file>.y
# YACC_SRCXX= <file>.ypp
# YACC_OUTPUT= Output file prefix, i.e, generates <prefix>.cpp <prefix>.h
# YACC_PREFIX= Yacc internal prefix, i.e., "yy" mapped to a specific prefix
# LEX_SRC= <file>.l
# LEX_OUTPUT= Output file prefix, i.e, generates <prefix>.cpp
# LEX_PREFIX= Lex internal prefix, i.e., "yy" mapped to a specific prefix
#
# In the simple case, you only need to set LIBNAME and SRCS
# for example,
#     LIBNAME=foo
#     SRCS=x.cpp y.cpp
#

##############################################
# Add custom targets below the following line.
include ../Makefile.rules

#
# You need to use double colon rules to add an additional "clean", "install",
# or "all" targets.
#
# for example:
#    clean::
#        rm foo
#
