#
#
#
include ../Makefile.defs

LIBNAME=defout
SRCS= defout.cpp defout_impl.cpp

##############################################
# Add custom targets below the following line.
include ../Makefile.rules
