#!/bin/ksh -p

# The following is for the Linux chkconfig utlility
# chkconfig: 35 99 01 
# description:  Athena License Daemon
#
# The following is for the Linux insserv utility
### BEGIN INIT INFO
# Provides: athena
# Default-Start: 3 5
# Default-Stop: 0 1 2 6
# Description: Start ADS License daemons
### END INIT INFO

# Source function library.
. /etc/init.d/functions

unset ENV

# Tool Configuration
# lic_tree=absolute path to Athena software release's License directory
# lic_file=absolute path to Athena provided license file
# log_dir=Directory for housing license daemon logs
# lic_log=Logfile name, default to athena.log
# Log_archive=Switch to enable license usage log, default to yes for enable

lic_tree=
lic_file=
log_dir=/var/tmp
lic_log=athena.log
Log_archive=yes

####### No User configuration after this line ####################

function die {
        echo "athena: $*" 1>&2
        exit 1
}

function startit {
	is_config
	is_up
	if [[ "$rstat" == "UP" ]] then
	die "Athena Daemon is already running"
	fi

	if [[ -e $log_dir/$lic_log && $Log_archive == "yes" ]] then
	stime=$(date '+%m%d%H%M')
	mv "$log_dir/$lic_log" "$log_dir/$lic_log-$stime"
	fi
	if [[ ! -e $lic_file && ! -r $lic_file ]] then
	die "Problem with License File: $lic_file"
	fi

	if [[ -e $lic_tree/bin ]] then
	cd $lic_tree/bin
	else
	die "FLEX tree not found"
	fi

	if [[ -w $log_dir ]] then
	lmgrd -c $lic_file -l $log_dir/$lic_log
	sleep 10
	else
	die "Unable to create log file $log_file"
	fi
}

function is_config {
	if [[ -z $lic_tree || -z $lic_file || -z $log_dir || -z $lic_log ]] then
	die "Please configure script before running"
	fi
}

function is_up {
	is_config
	run_stat=$( lmstat -a -c $lic_file | grep "athena:" )
	if [[ ! -z $run_stat ]] then
	rstat="UP"
	else
	rstat="DOWN"
	fi
}

function stopit {
	is_config
	is_up
	if [[ "$rstat" == "DOWN" ]] then
	die "Athena Daemon is not running"
	fi
	
	lmdown -c $lic_file -q
}

function ads_status {
	is_config
	lmstat -a -c $lic_file
}

function ads_reread {
	is_config
	is_up
	if [[ "$rstat" == "DOWN" ]] then
	echo "Athena License Daemon is not Running"
	echo "Starting Athena license daemon"
	startit
	else
	lmreread -c $lic_file
	fi
}

export PATH=$lic_tree/bin:$PATH

case "$1" in
        start) print "Starting Athena License Daemon"
		startit ; ads_status
		;;
        stop) print "Shutting down Athena License Daemon"
		stopit ;;
        reread) print "Rereading Athena License File"
		ads_reread ;;
        status) 
                ads_status
                ;;
          *) print "     Daemon Script for Athena License Server"
		print "     Usage:  athena "$"option"
                print "        "$"option = start, stop, status, reread"  ; exit ;
esac

