#!/bin/ksh -p

unset ENV

function die {
        echo "lsf: $*" 1>&2
        exit 1
}

# verify_env
# Check for valid software tree and existence of msh.conf
# Environment variable ADSHOME and MSHCONFIG must exist.
function verify_env {
ADSHOME=$(env | grep ADSHOME | cut -d"=" -f2)
MSHCONFIG=$(env | grep MSHCONFIG | cut -d"=" -f2)
if [[ -z "$ADSHOME" || -z "$MSHCONFIG" ]] then
	die "Environment Setup Missing: ADSHOME=$ADSHOME, MSHCONFIG=$MSHCONFIG"
fi

if [[ ! -d "$ADSHOME" || ! -f "$MSHCONFIG" ]] then
	die "Binary tree/file Missing: ADSHOME=$ADSHOME, MSHCONFIG=$MSHCONFIG"
fi
}


function get_lsf {

LSTOP=$(grep "lsf_top" $MSHCONFIG | awk '{print $2}')
if [[ $LSTOP = @('""'|''|'#') ]]
then
        die "LSF have not been configured for Athena Software Products! Please run configure from install directory"
fi

LSLIC=$(grep "lsf_lic" $MSHCONFIG | awk '{print $2}')
if [[ $LSLIC = @('""'|''|'#') ]]
then
        die "LSF have not been configured for Athena Software Products! Please run configure from install directory"
fi

LSPORT=`grep "lsf_port" $MSHCONFIG | awk '{print $2}'`
if [[ $LSPORT = @('""'|''|'#') ]]
then
        die "LSF have not been configured for Athena Software Products! Please run configure from install directory"
fi

LSQUEUE=`grep "queue" $MSHCONFIG | awk '{print $2}'`
if [[ $LSQUEUE = @('""'|''|'#') ]]
then
	die "LSF have not been configured for Athena Software Products! Please run configure from install directory"
fi

}

function lsf_health {

ISDAEMON=`$ADSHOME/license/bin/lmstat -c $LSPORT@$LSLIC | grep UP `
if [[ $ISDAEMON = '' ]]
then
        die "License DAEMON at $LSPORT@$LSLIC is down"
fi

ISLSCLIENT=`ps -ef | grep "etc/lim" | grep $LSTOP`
if [[ $ISLSCLIENT = '' ]]
then
	THISHOST=`hostname`
        die "LSF DAEMON is not running on $THISHOST"
fi

}

# Start of Program
#
verify_env

dir=`dirname $0`
case $dir in
        .) TOP=$(dirname $(pwd)) ;;
        *) TOP=$(dirname $dir) ;;
esac

# If site_conf is not user, we must use msh.conf from centralized location
conf_mode=$(grep "site_conf" $TOP/conf/msh.conf | awk '{print $2}')
if [[ $conf_mode != "user" && -e $TOP/conf/msh.conf ]] ; then
	MSHCONFIG=$TOP/msh.conf
fi

get_lsf
TT=$(env | grep LSF_ENVDIR )
if [[ $LSLIC != "Pass-Thru" || $LSPORT != "Pass-Thru" && ! -z $(env | grep LSF_ENVDIR ) ]] ; then
#lsf_health

	if [[ -e $LSTOP/conf/profile.lsf ]] ; then
		. $LSTOP/conf/profile.lsf
	else
		die "profile.lsf is not at $LSTOP/conf/profile.lsf"
	fi
fi

#fi


case "$1" in
	    x) exec ls $LSF_BINDIR ;;
	ksh*) echo shell; exec "$@" </dev/tty > /dev/tty 2>/dev/tty;;
	    *) exec "$@" ;;
esac
