#!/usr/bin/env tclsh
#
# create a simple license file.
# Do not rush to hack, since you do not know the salt!
# $Id: mklicense,v 1.3 2006/03/02 14:59:56 mmt Exp $

package require Itcl

set top [file dirname [file norm $argv0]]

set me [file normalize $argv0]

# -- do we run from the source tree?
if [string match *src/utils/mklicense $me] {
    source ../mtlib/object.tcl
    source ../mtlib/license.tcl
    #set lib [file dirname $top]
} else {
    set lib [file join [file dirname $top] lib]

set auto_path \
    [concat $lib [file join $lib zroute] [file join $lib mtlib] $auto_path]

}

proc warning {fac msg} {
	puts stderr "warning: $fac: $msg"
}

if { $argv == "" } {
	puts stderr "usage: mklicense salt < keyin > keyout"
	exit
}

LLicense lic -salt $argv

lic Read -
lic Write -
exit
