#!/bin/ksh -p
#
#
# just link any name to wrapper to make wrapper run ../bin.$ARCH/program
#
#
IS_LDPATH=$(echo $LD_LIBRARY_PATH | grep 'lib/lib-solaris')
#unset LD_LIBRARY_PATH
LC_ALL=C
export LC_ALL
args=$@
dir=`dirname $0`
case $dir in
        .) base=$(dirname $(dirname $(pwd))) ;;
        *) base=$(dirname $(dirname $dir)) ;;
esac

me=`basename $0`

os=`uname -s`.`uname -m`
case "$os" in
        Linux.*86)
		p=i386-linux
		if [ ! -z $IS_LDPATH ]
		then
		LDPATH=$LD_LIBRARY_PATH
		unset LD_LIBRARY_PATH
		ISLIB=`ldd $base/pubtools/i386-linux/bin/tclsh8.4 | /bin/grep found | /usr/bin/wc -l`
		LD_LIBRARY_PATH=$LDPATH
		else
		ISLIB=`ldd $base/pubtools/i386-linux/bin/tclsh8.4 | /bin/grep found | /usr/bin/wc -l`
		fi
		if [ $ISLIB != 0 ]; then
                xlib=$base/pubtools/$p/lib:$base/ads/$p/aim/lib:/lib:/usr/lib:$base/lib/lib-linux
        	else
		xlib=$base/pubtools/$p/lib:$base/ads/$p/aim/lib:/lib:/usr/lib
		fi
		;;
	Linux.x86_64)
		p=i386-linux
		xlib=$base/pubtools/$p/lib:$base/ads/$p/aim/lib:/lib:/usr/lib
		;;
	SunOS.sun4u)
		p=sun4u-sparc
		xlib=$base/pubtools/$p/lib:$base/ads/$p/aim/lib:/lib:/usr/lib:$base/lib/lib-solaris
		;;
                *) echo "$me: unsupported OS/platform: $os" 1>&2 ; exit -1;;
esac

f=$base/ads/$p/aim/bin/$me
if [ ! -z $ADS_LD_LIBRARY_PATH ]
then
export LD_LIBRARY_PATH=$xlib:$ADS_LD_LIBRARY_PATH
else
export LD_LIBRARY_PATH=$xlib
fi

test -f $f || {
        echo "$me: cannot locate $f"
        exit 1
}
exec $f "$@"
