#!/bin/sh
# \
	exec tclsh $0 ${@+"$@"}

set top [file dirname [file normalize $argv0]]
if [file exists $top/Makefile] {
    set lib [file dirname $top]
} else {
    set lib [file join [file dirname $top] lib]
}
lappend auto_path $lib

package require mtlib 1.0
package require RTI 1.0
#
#       Class: Prog
# Description:
#      Author: Manolis M. Tsangaris
#
itcl::class Prog {
	inherit LProgram
    # -------------------------------------------------- Public Variables --
    # -------------------------------------------------- Public Methods ----
    # -------------------------------------------------- Virtual Methods ---
    # -------------------------------------------------- Protected Variables 
	protected variable rti ""
    # -------------------------------------------------- Common Variables --
    # -------------------------------------------------- Configuration -----
    constructor {args} {
		eval configure $args
		option help -help "command help"
        option address -w {port[@host]} "rti server address" 7840
	}
    destructor {
		$rti delete
	}
    # -------------------------------------------------- Private Methods ---
	# ----------------------------------------------- Interface Implementation
	protected method vRun {opt} {
		upvar $opt OPT
		if { $OPT(help) } { Usage ; return }
		global gRTI

		set rti [RTI $this.r#auto -opts [array get OPT]]
		set gRTI $rti
		after 1000 "expr 1/0.0"
		$rti Wait
	}
    # -------------------------------------------------- Common Initialization
}
proc bgerror {err} {
    global errorInfo
    global gRTI
    $gRTI ReportError $err $errorInfo
}
proc error {err} {
    global errorInfo
    global gRTI
    $gRTI ReportError $err $errorInfo
}

Prog pm
pm Run
pm delete
exit
