#!/bin/sh
#
# \
	exec tclsh $0 "$@"
package require Itcl

set top [file dirname [file normalize $argv0]]
if [file exists $top/Makefile] {
    set lib [file dirname $top]
} else {
    set lib [file join [file dirname $top] lib]
}
lappend auto_path $lib

package require mtlib 1.0
package require RTID 1.0

#
#       Class: Prog
# Description:
#      Author: Manolis M. Tsangaris
#
itcl::class Prog {
	inherit LProgram
    # -------------------------------------------------- Public Variables --
    # -------------------------------------------------- Public Methods ----
    # -------------------------------------------------- Virtual Methods ---
    # -------------------------------------------------- Protected Variables 
    # -------------------------------------------------- Common Variables --
    # -------------------------------------------------- Configuration -----
    constructor {args} {
		eval configure $args
		option help -help "command help"
		option address -w {port[@host]} "server address" 7840
	}
    destructor { }
    # -------------------------------------------------- Private Methods ---
	# ----------------------------------------------- Interface Implementation
	protected method vRun {opt} {
		upvar $opt OPT

		set rtins [RTINS $this.rtins -opts [array get OPT]]
		$rtins Wait
	}
    # -------------------------------------------------- Common Initialization
}

Prog pm
pm Run
pm delete
exit
