#!/bin/sh
# \
	exec wish $0 -- ${@+"$@"}

set top [file dirname [file normalize $argv0]]
if [file exists $top/Makefile] {
    set lib [file dirname $top]
} else {
    set lib [file join [file dirname $top] lib]
}
lappend auto_path $lib

package require mtlib 1.0
package require URTI 1.0
#
#       Class: Prog
# Description:
#      Author: Manolis M. Tsangaris
#
itcl::class Prog {
	inherit LProgram
    # -------------------------------------------------- Public Variables --
    # -------------------------------------------------- Public Methods ----
    # -------------------------------------------------- Virtual Methods ---
    # -------------------------------------------------- Protected Variables 
	protected variable rti ""
    # -------------------------------------------------- Common Variables --
    # -------------------------------------------------- Configuration -----
    constructor {args} {
		eval configure $args
		option help -help "command help"
        option address -w {port[@host]} "rti server address" 7840
		wm withdraw .
	}
    destructor {
		$rti delete
	}
    # -------------------------------------------------- Private Methods ---
	# ----------------------------------------------- Interface Implementation
	protected method vRun {opt} {
		upvar $opt OPT
		if { $OPT(help) } { Usage ; return }

		set rti [URTI .r#auto -opts [array get OPT]]
		$rti Wait
	}
    # -------------------------------------------------- Common Initialization
}
Prog pm
pm Run
pm delete
exit
